language: node_js
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - g++-4.8
      - gcc-4.8

services:
  - mysql
  - postgresql

node_js:
  - '8'
  - '8.10' # AWS Lambda
  - '9'
  - '10' # AWS Lambda
  - '11'
  - '12'
  - 'node'

install:
  - npm install

script:
  - npm run ci

env:
  - DB=sqlite3
  - DB=mysql
  - DB=mysql2
  - DB=postgres

before_install:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS test_mysql;'; fi"
  - sh -c "if [ '$DB' = 'mysql2' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS test_mysql2;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database test_postgres;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'oracledb' ]; then wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh; fi"
  - sh -c "if [ '$DB' = 'oracledb' ]; then bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh; fi"

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then npm install mysql; fi"
  - sh -c "if [ '$DB' = 'mysql2' ]; then npm install mysql2; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then npm install pg; fi"
  - sh -c "if [ '$DB' = 'oracledb' ]; then npm install oracledb; fi"
