language: node_js
node_js:
  - "4"
  - "5"
  - "6.9.1"
  - "6.9.2"
  - "6.9.3"
  - "6.9.4"
  - "6.9.5"
  - "6"
  - "7.3.0"
  - "7.4.0"
  - "7.5.0"
  - "7"
  - "node"
  - "iojs"

matrix:
  allow_failures:
    - node_js: "4"
    - node_js: "5"
    - node_js: "iojs"
